/**
 * G-code line formatting utilities for Maslow 4 CNC.
 * Only emits Maslow-compatible commands: G0, G1, G2, G3, G17, G21, M03, M05.
 */

export function formatCoord(v: number): string {
  return v.toFixed(3);
}

export function rapid(x: number, y: number): string {
  return `G0 X${formatCoord(x)} Y${formatCoord(y)}`;
}

export function rapidZ(z: number): string {
  return `G0 Z${formatCoord(z)}`;
}

export function linearMove(x: number, y: number, feedRate: number): string {
  return `G1 X${formatCoord(x)} Y${formatCoord(y)} F${feedRate.toFixed(0)}`;
}

export function plunge(z: number, feedRate: number): string {
  return `G1 Z${formatCoord(z)} F${feedRate.toFixed(0)}`;
}

export function gcodeHeader(rpm: number): string[] {
  return [
    '; Generated by Maslow CNC Studio',
    `; Date: ${new Date().toISOString()}`,
    '',
    'G17 ; XY plane',
    'G21 ; Millimeters',
    'G90 ; Absolute positioning',
    `M03 S${rpm} ; Spindle on`,
    '',
  ];
}

export function gcodeFooter(safeHeight: number): string[] {
  return [
    '',
    'M05 ; Spindle off',
    `G0 Z${formatCoord(safeHeight)} ; Retract to safe height`,
    'G0 X0 Y0 ; Return home',
    '; End of program',
  ];
}

export async function downloadGcode(lines: string[], filename: string): Promise<void> {
  const { saveGcodeFile } = await import('../utils/fileSave');
  const content = lines.join('\n');
  await saveGcodeFile(content, filename);
}
